# Numpy

## DUCAT ML Class 2

- https://cs231n.github.io/python-numpy-tutorial/

Random Function

In [4]:
import numpy as np
import random

In [5]:
# random 0 to 1
np.random.random(size = 5)

array([0.43715397, 0.86067028, 0.25551648, 0.70154655, 0.79236148])

In [6]:
for i in range(5):
  print(np.random.uniform(0.7,1))

0.708043689767402
0.7464836123803584
0.895918580790264
0.9990986259062514
0.7864721039876622


In [7]:
for i in range(1):
  print(np.random.rand(8))

[0.75257341 0.29613834 0.06511037 0.06521986 0.83335229 0.25777392
 0.42640026 0.52965669]


In [8]:
np.random.randint(1000,9999,size=5)

array([4281, 8112, 8972, 2622, 2465])

In [9]:
n1= [12,34,55,66,12,33,44,55,6,88,56,78,12]

np.random.choice(n1,size=5)

array([33, 56, 66, 44, 78])

Numpy array

In [10]:
n1 = np.array([12,33,44,55,78,99,23,46,77])
n1, type(n1), n1.shape, n1.size, n1.ndim

(array([12, 33, 44, 55, 78, 99, 23, 46, 77]), numpy.ndarray, (9,), 9, 1)

In [11]:
n1[0], n1[-1], n1[:4], n1[::-1]

(np.int64(12),
 np.int64(77),
 array([12, 33, 44, 55]),
 array([77, 46, 23, 99, 78, 55, 44, 33, 12]))

In [12]:
n1[0] = 56
n1, n1[n1>50]

(array([56, 33, 44, 55, 78, 99, 23, 46, 77]), array([56, 55, 78, 99, 77]))

In [13]:
n1# Create a numpy array
array_2d = np.array([[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]])

# Print the array
print("Numpy array:")
print(array_2d)

# Get the shape
shape = array_2d.shape
print("\nShape of the array:", shape)

Numpy array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Shape of the array: (3, 4)


In [14]:
array_2d.ndim, array_2d.size

(2, 12)

In [15]:
array_2d[0,0], array_2d[1:, 1:], array_2d[:, -1]

(np.int64(1),
 array([[ 6,  7,  8],
        [10, 11, 12]]),
 array([ 4,  8, 12]))

In [16]:
array_2d[array_2d % 2 !=0]

array([ 1,  3,  5,  7,  9, 11])

In [17]:
from time import sleep

for i in range(array_2d.shape[0]):
  for j in range(array_2d.shape[1]):
    if array_2d[i,j]%2==0:
      print(array_2d[i,j],end=" ")
    sleep(0.5)
  print()

2 4 
6 8 
10 12 


In [18]:
array_2d[::-1, ::-1]

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

### Math Operations and Matrix Multiplication

In [19]:
import numpy as np

X = np.array([[1, 2], [3, 4]])
Y = np.array([[5, 6], [7, 8]])

print(X,"\n", Y)
print("\n", X * Y, "\n",  Y * X)

print("\n", X @ Y, "\n", np.dot(X, Y), "\n", np.matmul(X, Y))

print("\n", Y @ X, "\n", np.dot(Y, X), "\n", np.matmul(Y, X))


[[1 2]
 [3 4]] 
 [[5 6]
 [7 8]]

 [[ 5 12]
 [21 32]] 
 [[ 5 12]
 [21 32]]

 [[19 22]
 [43 50]] 
 [[19 22]
 [43 50]] 
 [[19 22]
 [43 50]]

 [[23 34]
 [31 46]] 
 [[23 34]
 [31 46]] 
 [[23 34]
 [31 46]]


List / Arrays

In [20]:
A = [[6, 7, 2],
      [8, 9, 4]]

print("element :", np.array(A) [1,0],'length :', len(A),'breadth :', len(A[1]))

element : 8 length : 2 breadth : 3


In [21]:
B = [[1, 2],  [2, 4], [3, 6]]

print(np.dot(A,B)) # same as print(np.matmul(A,B))
print(np.dot(B,A))

[[26 52]
 [38 76]]
[[22 25 10]
 [44 50 20]
 [66 75 30]]


In [22]:
print(np.multiply(B,B))  # errors on print(B * B)

[[ 1  4]
 [ 4 16]
 [ 9 36]]


In [23]:
C = np.array([[1, 2],  [2, 4], [3, 6]])
print(C * C)

[[ 1  4]
 [ 4 16]
 [ 9 36]]


Arange

In [24]:
n1 = np.arange(2,14).reshape(4,3)
n2 = np.arange(10,22).reshape(4,3)
n1, n2

(array([[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10],
        [11, 12, 13]]),
 array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21]]))

In [25]:
np.add(n1, n2), np.subtract(n2, n1), np.multiply(n1, n2)

(array([[12, 14, 16],
        [18, 20, 22],
        [24, 26, 28],
        [30, 32, 34]]),
 array([[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]]),
 array([[ 20,  33,  48],
        [ 65,  84, 105],
        [128, 153, 180],
        [209, 240, 273]]))

In [26]:
n1 + n2, n2 - n1, n1 * n2, n2 // n1

(array([[12, 14, 16],
        [18, 20, 22],
        [24, 26, 28],
        [30, 32, 34]]),
 array([[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]]),
 array([[ 20,  33,  48],
        [ 65,  84, 105],
        [128, 153, 180],
        [209, 240, 273]]),
 array([[5, 3, 3],
        [2, 2, 2],
        [2, 1, 1],
        [1, 1, 1]]))

In [27]:
n1.T

array([[ 2,  5,  8, 11],
       [ 3,  6,  9, 12],
       [ 4,  7, 10, 13]])

In [28]:
np.concatenate((n1,n2),axis=0)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [29]:
np.concatenate((n1,n2),axis=1)

array([[ 2,  3,  4, 10, 11, 12],
       [ 5,  6,  7, 13, 14, 15],
       [ 8,  9, 10, 16, 17, 18],
       [11, 12, 13, 19, 20, 21]])

In [30]:
n1.max(), n1.max(axis = 1), n1.max(axis = 0), n1.sum(), n1.mean()

(np.int64(13),
 array([ 4,  7, 10, 13]),
 array([11, 12, 13]),
 np.int64(90),
 np.float64(7.5))

Inverse of Matrix

In [37]:
n1 = 1997
n2 = 904
n3 = 906
n4 = 32

x = np.array([[n4+n1, n1, n1],[n2, n4+n2,n2],[n3,n3,n3+n4]])

x

array([[2029, 1997, 1997],
       [ 904,  936,  904],
       [ 906,  906,  938]])

In [38]:
y = np.array([n1,n2,n3])
y

array([1997,  904,  906])

In [39]:
print(np.linalg.inv(x))

[[ 0.01499414 -0.01625586 -0.01625586]
 [-0.00735869  0.02389131 -0.00735869]
 [-0.00737497 -0.00737497  0.02387503]]


In [40]:
np.dot(y.T,np.linalg.inv(x))

array([ 16.60932209, -17.54692791, -17.48442791])