# Tensors

In [1]:
import torch

input = torch.rand(2, 3, 4)
mat2 = torch.rand(2, 4, 5)
res = torch.bmm(input, mat2)
some = input @ mat2
res.size()

torch.Size([2, 3, 5])

In [2]:
res, some

(tensor([[[1.2838, 1.0240, 2.0250, 1.4554, 1.5545],
          [0.6875, 0.6156, 1.3922, 1.0115, 0.9728],
          [0.9845, 0.6137, 1.7409, 1.1733, 1.3073]],
 
         [[1.0667, 1.2366, 1.3915, 2.0924, 1.2289],
          [0.7661, 0.6912, 0.6546, 0.9166, 0.5929],
          [0.2569, 0.1614, 0.4368, 0.4524, 0.2084]]]),
 tensor([[[1.2838, 1.0240, 2.0250, 1.4554, 1.5545],
          [0.6875, 0.6156, 1.3922, 1.0115, 0.9728],
          [0.9845, 0.6137, 1.7409, 1.1733, 1.3073]],
 
         [[1.0667, 1.2366, 1.3915, 2.0924, 1.2289],
          [0.7661, 0.6912, 0.6546, 0.9166, 0.5929],
          [0.2569, 0.1614, 0.4368, 0.4524, 0.2084]]]))

**Affine transformation**
- affine_func: Uses the standard formula y = xTw + b directly.
- linear_func: Converts the affine transformation into a pure matrix multiplication by augmenting the data with a constant 1 and the weights with the bias.
- This is a common trick in machine learning to unify affine and linear transformations so you can implement them with a single matrix multiplication.

In [3]:
import torch
def affine_func(w, x, b):
    result_by_affine = torch.mm(x.T,w)+b
    print("result_by_affine:\n",result_by_affine)
def linear_func(w, x, b):
    mat_ones = torch.ones(x.shape[1]).unsqueeze(0)
    mat_x_1 = torch.cat((x,mat_ones),0)
    mat_w_b = torch.cat((w,torch.tensor([b]).unsqueeze(0)),0)

    result_by_linear = torch.mm(mat_x_1.T, mat_w_b)
    print("\nresult_by_linear:\n",result_by_linear)

w = torch.tensor([1.,2.]).unsqueeze(1)
x = torch.randn([2,3])
b = 4.
affine_func(w,x,b)
linear_func(w,x,b)

result_by_affine:
 tensor([[4.7781],
        [7.4152],
        [3.0604]])

result_by_linear:
 tensor([[4.7781],
        [7.4152],
        [3.0604]])
